package fmod_ex

// #include "fmod_errors.h"
import "C"

const VERSION = C.FMOD_VERSION

type InitFlags C.FMOD_INITFLAGS

const (
  INIT_NORMAL                    InitFlags = C.FMOD_INIT_NORMAL
  INIT_STREAM_FROM_UPDATE                  = C.FMOD_INIT_STREAM_FROM_UPDATE
  INIT_3D_RIGHTHANDED                      = C.FMOD_INIT_3D_RIGHTHANDED
  INIT_SOFTWARE_DISABLE                    = C.FMOD_INIT_SOFTWARE_DISABLE
  INIT_OCCLUSION_LOWPASS                   = C.FMOD_INIT_OCCLUSION_LOWPASS
  INIT_HRTF_LOWPASS                        = C.FMOD_INIT_HRTF_LOWPASS
  INIT_DISTANCE_FILTERING                  = C.FMOD_INIT_DISTANCE_FILTERING
  INIT_SOFTWARE_REVERB_LOWMEM              = C.FMOD_INIT_SOFTWARE_REVERB_LOWMEM
  INIT_ENABLE_PROFILE                      = C.FMOD_INIT_ENABLE_PROFILE
  INIT_VOL0_BECOMES_VIRTUAL                = C.FMOD_INIT_VOL0_BECOMES_VIRTUAL
  INIT_WASAPI_EXCLUSIVE                    = C.FMOD_INIT_WASAPI_EXCLUSIVE
  INIT_PS3_PREFERDTS                       = C.FMOD_INIT_PS3_PREFERDTS
  INIT_PS3_FORCE2CHLPCM                    = C.FMOD_INIT_PS3_FORCE2CHLPCM
  INIT_DISABLEDOLBY                        = C.FMOD_INIT_DISABLEDOLBY
  INIT_SYSTEM_MUSICMUTENOTPAUSE            = C.FMOD_INIT_SYSTEM_MUSICMUTENOTPAUSE
  INIT_SYNCMIXERWITHUPDATE                 = C.FMOD_INIT_SYNCMIXERWITHUPDATE
  INIT_GEOMETRY_USECLOSEST                 = C.FMOD_INIT_GEOMETRY_USECLOSEST
  INIT_DISABLE_MYEARS_AUTODETECT           = C.FMOD_INIT_DISABLE_MYEARS_AUTODETECT
)

type OutputType C.FMOD_OUTPUTTYPE

const (
  OUTPUTTYPE_AUTODETECT    OutputType = C.FMOD_OUTPUTTYPE_AUTODETECT
  OUTPUTTYPE_UNKNOWN                  = C.FMOD_OUTPUTTYPE_UNKNOWN
  OUTPUTTYPE_NOSOUND                  = C.FMOD_OUTPUTTYPE_NOSOUND
  OUTPUTTYPE_WAVWRITER                = C.FMOD_OUTPUTTYPE_WAVWRITER
  OUTPUTTYPE_NOSOUND_NRT              = C.FMOD_OUTPUTTYPE_NOSOUND_NRT
  OUTPUTTYPE_WAVWRITER_NRT            = C.FMOD_OUTPUTTYPE_WAVWRITER_NRT
  OUTPUTTYPE_DSOUND                   = C.FMOD_OUTPUTTYPE_DSOUND
  OUTPUTTYPE_WINMM                    = C.FMOD_OUTPUTTYPE_WINMM
  OUTPUTTYPE_WASAPI                   = C.FMOD_OUTPUTTYPE_WASAPI
  OUTPUTTYPE_ASIO                     = C.FMOD_OUTPUTTYPE_ASIO
  OUTPUTTYPE_OSS                      = C.FMOD_OUTPUTTYPE_OSS
  OUTPUTTYPE_ALSA                     = C.FMOD_OUTPUTTYPE_ALSA
  OUTPUTTYPE_ESD                      = C.FMOD_OUTPUTTYPE_ESD
  OUTPUTTYPE_PULSEAUDIO               = C.FMOD_OUTPUTTYPE_PULSEAUDIO
  OUTPUTTYPE_COREAUDIO                = C.FMOD_OUTPUTTYPE_COREAUDIO
  OUTPUTTYPE_XBOX360                  = C.FMOD_OUTPUTTYPE_XBOX360
  OUTPUTTYPE_PSP                      = C.FMOD_OUTPUTTYPE_PSP
  OUTPUTTYPE_PS3                      = C.FMOD_OUTPUTTYPE_PS3
  OUTPUTTYPE_NGP                      = C.FMOD_OUTPUTTYPE_NGP
  OUTPUTTYPE_WII                      = C.FMOD_OUTPUTTYPE_WII
  OUTPUTTYPE_3DS                      = C.FMOD_OUTPUTTYPE_3DS
  OUTPUTTYPE_AUDIOTRACK               = C.FMOD_OUTPUTTYPE_AUDIOTRACK
  OUTPUTTYPE_OPENSL                   = C.FMOD_OUTPUTTYPE_OPENSL
  OUTPUTTYPE_NACL                     = C.FMOD_OUTPUTTYPE_NACL
  OUTPUTTYPE_WIIU                     = C.FMOD_OUTPUTTYPE_WIIU
  OUTPUTTYPE_MAX                      = C.FMOD_OUTPUTTYPE_MAX
)

type Mode C.FMOD_MODE

const (
  MODE_DEFAULT                Mode = C.FMOD_DEFAULT
  MODE_LOOP_OFF                    = C.FMOD_LOOP_OFF
  MODE_LOOP_NORMAL                 = C.FMOD_LOOP_NORMAL
  MODE_LOOP_BIDI                   = C.FMOD_LOOP_BIDI
  MODE_2D                          = C.FMOD_2D
  MODE_3D                          = C.FMOD_3D
  MODE_HARDWARE                    = C.FMOD_HARDWARE
  MODE_SOFTWARE                    = C.FMOD_SOFTWARE
  MODE_CREATESTREAM                = C.FMOD_CREATESTREAM
  MODE_CREATESAMPLE                = C.FMOD_CREATESAMPLE
  MODE_CREATECOMPRESSEDSAMPLE      = C.FMOD_CREATECOMPRESSEDSAMPLE
  MODE_OPENUSER                    = C.FMOD_OPENUSER
  MODE_OPENMEMORY                  = C.FMOD_OPENMEMORY
  MODE_OPENMEMORY_POINT            = C.FMOD_OPENMEMORY_POINT
  MODE_OPENRAW                     = C.FMOD_OPENRAW
  MODE_OPENONLY                    = C.FMOD_OPENONLY
  MODE_ACCURATETIME                = C.FMOD_ACCURATETIME
  MODE_MPEGSEARCH                  = C.FMOD_MPEGSEARCH
  MODE_NONBLOCKING                 = C.FMOD_NONBLOCKING
  MODE_UNIQUE                      = C.FMOD_UNIQUE
  MODE_3D_HEADRELATIVE             = C.FMOD_3D_HEADRELATIVE
  MODE_3D_WORLDRELATIVE            = C.FMOD_3D_WORLDRELATIVE
  MODE_3D_INVERSEROLLOFF           = C.FMOD_3D_INVERSEROLLOFF
  MODE_3D_LINEARROLLOFF            = C.FMOD_3D_LINEARROLLOFF
  MODE_3D_LINEARSQUAREROLLOFF      = C.FMOD_3D_LINEARSQUAREROLLOFF
  MODE_3D_CUSTOMROLLOFF            = C.FMOD_3D_CUSTOMROLLOFF
  MODE_3D_IGNOREGEOMETRY           = C.FMOD_3D_IGNOREGEOMETRY
  MODE_UNICODE                     = C.FMOD_UNICODE
  MODE_IGNORETAGS                  = C.FMOD_IGNORETAGS
  MODE_LOWMEM                      = C.FMOD_LOWMEM
  MODE_LOADSECONDARYRAM            = C.FMOD_LOADSECONDARYRAM
  MODE_VIRTUAL_PLAYFROMSTART       = C.FMOD_VIRTUAL_PLAYFROMSTART
)

type ChannelIndex int

const (
  CHANNEL_FREE  ChannelIndex = C.FMOD_CHANNEL_FREE
  CHANNEL_REUSE              = C.FMOD_CHANNEL_REUSE
)
